/**
 * Nội dung "Conversation Escalation & Support Summary": khối văn bản khách SAO CHÉP gửi cho đội hỗ trợ kỹ thuật
 * (@interlink_technicalsupport) khi bot không giải quyết được. Ghép hoàn toàn bằng CODE từ dữ liệu đã có sẵn, KHÔNG
 * gọi thêm LLM riêng cho việc này (tái dùng bản tóm tắt cuộn `EpisodeSummary` đã được `cleanSummary` kiểm chứng —
 * không số liệu bịa — cùng sự kiện `template_sent` do code ghi), nên không có nguy cơ bịa nội dung.
 *
 * Phạm vi (Conversation Scope) do EpisodeManager quyết định TỪ TRƯỚC: một episode = một vấn đề (tách theo
 * topic_group / khoảng lặng T_gap), nên chỉ cần truyền đúng episode đang mở là tự động đúng phạm vi — không lấy
 * các vấn đề cũ của khách.
 *
 * Viết bằng tiếng Anh: đội hỗ trợ dùng tiếng Anh nội bộ, và khối này KHÔNG đi qua bước dịch lại (validator dịch có
 * thể tự làm sai lệch số liệu — xem translationProblems/canonicalNumber) nên giữ nguyên văn là an toàn nhất.
 */
import type { EpisodeSummary } from "./summary";

export interface HandoffInput {
  /** Vấn đề: ưu tiên chủ đề episode đang mở, sau đó tới issue trong bản tóm tắt. */
  issue?: string | null;
  summary?: EpisodeSummary;
  /** Các bước bot đã hướng dẫn trong CHÍNH episode này, theo thời gian (code ghi từ event `template_sent`). */
  stepsSent: string[];
  ticketId?: number | null;
}

const HEADER = "InterLink support handoff (auto-generated by the bot — please review before replying)";
const FOOTER = "Status: the bot could not resolve this — a human agent is needed.";

/** true = có đủ nội dung đáng gửi (không sinh khối trống/vô nghĩa cho một câu bot chưa hiểu được ngay từ đầu). */
export function hasHandoffContent(inp: HandoffInput): boolean {
  return !!(inp.issue?.trim() || inp.summary?.user_reported || inp.summary?.exact_facts.length || inp.stepsSent.length || inp.summary?.unresolved_points);
}

export function buildHandoffText(inp: HandoffInput): string {
  const lines: string[] = [HEADER];
  if (inp.ticketId) lines.push(`Ticket: #${inp.ticketId}`);
  const issue = inp.issue?.trim() || inp.summary?.issue;
  if (issue) lines.push(`Issue: ${issue}`);
  if (inp.summary?.user_reported) lines.push(`Customer reported: ${inp.summary.user_reported}`);
  if (inp.stepsSent.length) lines.push(`Bot guidance already given:\n${inp.stepsSent.map((s, i) => `  ${i + 1}. ${s}`).join("\n")}`);
  if (inp.summary?.exact_facts.length) lines.push(`Details provided by the customer: ${inp.summary.exact_facts.join(" · ")}`);
  if (inp.summary?.unresolved_points) lines.push(`Still unresolved: ${inp.summary.unresolved_points}`);
  lines.push(FOOTER);
  return lines.join("\n");
}
