/** Tên hiển thị tiếng Việt của từng template (theo tình huống của khách) — dùng cho các báo cáo gửi người không rành kỹ thuật. */
export const TEMPLATE_TITLES: Record<string, string> = {
  "fp-1-greeting": "Khách chào", "greeting-returning": "Khách quay lại khi đang có vụ việc cũ", "you-are-welcome": "Khách cảm ơn",
  "how-to-sign-up": "Cách đăng ký tài khoản", "how-to-login": "Cách đăng nhập", "forgot-login-id": "Quên ID đăng nhập",
  "esc-forgot-password": "Quên mật khẩu", "esc-login-fail": "Đăng nhập / quét mặt thất bại", "face-scan-black-screen": "Quét mặt bị màn hình đen",
  "otp-email": "Không nhận được mã OTP qua email", "otp-telegram": "Không nhận được mã OTP qua Telegram", "fp-7-change-email": "Đổi email",
  "email-old-email-required": "Đổi email nhưng không còn email cũ", "fp-10-change-id": "Đổi ID", "fp-9-delete-account": "Xoá tài khoản",
  "twin-account": "Anh chị em sinh đôi / cùng khuôn mặt", "referral-code": "Nhập mã giới thiệu (referral code)",
  "fp-5-how-to-kyc": "Cách làm KYC", "fp-5b-kyc-email-queue": "Đã nhận email KYC nhưng app vẫn đang chờ", "fp-6-kyc-slow": "Chờ lâu chưa được curator chọn",
  "fp-6b-kyc-review-long": "KYC xét duyệt lâu / muốn đẩy nhanh / đã xong bước 1", "kyc-matched-not-verified": "Đã được curator chọn nhưng chưa được xác minh",
  "fp-2-withdraw": "Rút tiền", "fp-3-listing-tge": "Niêm yết sàn / TGE", "fp-4-itlg-burn": "Tại sao ITLG bị trừ (burn)",
  "itlg-recover-after-burn": "Lấy lại ITLG đã bị burn", "itlg-mining-reduced-50": "Tại sao khai thác được ít ITLG hơn (giảm 50%)", "itlg-earn-more": "Cách kiếm thêm ITLG",
  "esc-mining-bug": "Lỗi khai thác (không cộng ITLG, HHP reset)", "esc-token-missing": "Token / faucet chưa về",
  "wallet-create": "Cách tạo ví", "esc-wallet-create": "Tạo ví bị lỗi", "wallet-reset-lost": "Mất ví sau khi xoá app / reset ví",
  "wallet-check-seedphrase": "Cách xem seed phrase / private key", "wallet-address": "Cách xem địa chỉ ví", "wallet-connect-social": "Kết nối mạng xã hội",
  "wallet-visa-card": "Đăng ký thẻ Visa", "wallet-swap-token-missing": "Swap xong không thấy token nhận", "esc-swap": "Swap bị lỗi / bị kẹt",
  "hcs-formula": "Công thức tính HCS", "hcs-low": "HCS thấp dù nhiều ITLG", "hcs-wallet-not-added": "HCS chưa được cộng ở ví",
  "hcs-multiple-wallets": "Liên kết nhiều ví có cộng HCS không", "esc-hcs-app": "HCS trong app không cộng / không tăng",
  "game-slime-cloud": "Đám mây slime trong game", "game-upgrade-max": "Không nâng cấp được vật phẩm", "weekly-reward-schedule": "Chưa nhận thưởng tuần / tháng",
  "esc-game-bug": "Lỗi game (điểm chưa cộng, submit lỗi)", "group-mining-create": "Tạo / tham gia Group Mining",
  "fp-11-ambassador": "Muốn làm Ambassador", "fp-11b-campaign-10m-nft": "Chưa nhận NFT của Campaign 10M", "whitepaper-general": "Hỏi chung về dự án InterLink",
  "fp-12-escalate": "Câu chuyển nhân viên (dùng chung)", "esc-app-error-image": "Khách gửi ảnh báo lỗi trong app",
  "fp-0-security-alert": "Cảnh báo khi khách lộ seed phrase / private key", "fp-0-owner-notice": "Báo cho owner khi có cảnh báo bảo mật",
  "antispam-1": "Chống spam — nhắc lần 1", "antispam-2": "Chống spam — cảnh báo lần 2", "antispam-3": "Chống spam — chặn 1 phút",
  "antispam-4": "Chống spam — chặn 10 phút", "antispam-5": "Chống spam — chặn 30 phút", "antispam-6": "Chống spam — chặn 1 giờ",
  "antispam-7plus": "Chống spam — chặn 24 giờ", "high-traffic": "Hệ thống quá tải", "image-unreadable": "Ảnh không đọc được",
  "image-cover-secret": "Nhắc che thông tin nhạy cảm trong ảnh", "admin-console-moved": "Thông báo trang quản trị đã chuyển lên web",
  "fp-8-forgot-id": "Quên ID", "itlg-to-itl-conversion": "Chuyển ITLG sang ITL", "itlg-burn-despite-mining": "Khai thác đều mà vẫn bị trừ ITLG",
  "esc-weekly-reward": "Chưa nhận thưởng tuần (chuyển nhân viên)",
};
